<?php
	$add_idioma = array(
		'en_EN' => array(
			'cod_pais' => 'EN',
			'idioma' => 'English',
			'idioma_config' => 'Language',
			'Inicio' => 'Home',
			'iniciar_session' => 'Login',
			'Nombre_de_usuario' => 'Username',
			'contra' => 'Password',
			'perfil' => 'Profile',
			'config' => 'Configuration',
			'cerrar_sesion' => 'Logout',
			'correo_electronico' => 'Email',
			'nombre' => 'Name',
			'1mes' => 'January',
			'2mes' => 'February',
			'3mes' => 'March',
			'4mes' => 'April',
			'5mes' => 'May',
			'6mes' => 'June',
			'7mes' => 'July',
			'8mes' => 'August',
			'9mes' => 'September',
			'10mes' => 'October',
			'11mes' => 'November',
			'12mes' => 'December',
			'Informacion personal' => 'Personal information',
			'Informacion de la cuenta' => 'Account information',
			'formato_fecha' => 'DD/MMMM/YY',
			'Quienes somos' => 'About us',
			'Las razones porque ser parte de esta gran red hecha espesialmente para ti' => 'The reasons for being part of this great network espesialmente made ​​for you',

			'Agrega a' => 'Add to',
			'Hola' => 'Hello',
			'publiquemos algo?' => 'Publish something?',
			'La contraseña o el nombre de usuario es incorrecta' => 'The password or the username is incorrect',
			'Escritorio' => 'Desk',
			'Fotos' => 'Photos',
			'Información' => 'Information',
			'Configurar' => 'Set up',
			'Fecha de nacimiento' => 'Birthdate',
			'Apellido:' => 'Last name',
			'General' => 'General',
			'Seguridad' => 'Segurity',
			'Hubo un problema inesperado.' => 'There was an unexpected problem',
			'Pais' => 'Country',
			'Genero' => 'Gender',
			'Correo' => 'E-mail',
			'Contraseña' => 'password',
			'Cambiar informacion personal' => 'Change personal information',
			'Nombre' => 'Name',
			'Cambiar contraseña' => 'Change Password',
			'Contraseña nueva' => 'New password',
			'Repetir contraseña' => 'Repeat password',
			'Cambiar nombre' => 'Change name',
			'Ingrese su apellido' => 'Enter your name',
			'El nombre se a cambiado' => 'The name is changed',
			'Ingrese su nombre' => 'Enter your name',
			'Hubo un problema' => 'There was a problem',
			'Hombre' => 'Man',
			'Mujer' => 'Woman',
			'Tema' => 'Theme',
			'Regístrate' => 'Sign up',


		)
	);
?>